/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.loss.maps.view;

import org.loss.maps.controller.ViewMap1841720019Sultan;

import java.awt.*;

/**
 * @author kaito
 */
public class Main1841720019Sultan extends javax.swing.JFrame {
    ViewMap1841720019Sultan vm = new ViewMap1841720019Sultan();

    /**
     * Creates new form Main1841720019Sultan
     */
    public Main1841720019Sultan() {
        super("Maps Viewer");
        this.setPreferredSize(Toolkit.getDefaultToolkit().getScreenSize());
        this.setLocationRelativeTo(null);
        initComponents();
        mPanelMaps.setSize(super.getWidth(), super.getHeight() - mMenuBar.getHeight());
        mPanelMaps.add(vm.createMapSultan(mPanelMaps.getWidth(), mPanelMaps.getHeight()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mPanelMaps = new javax.swing.JPanel();
        mMenuBar = new javax.swing.JMenuBar();
        mMenuFile = new javax.swing.JMenu();
        mMenuItemList = new javax.swing.JMenuItem();
        mMenuItemUpload = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Maps");
        setExtendedState(6);

        javax.swing.GroupLayout mPanelMapsLayout = new javax.swing.GroupLayout(mPanelMaps);
        mPanelMaps.setLayout(mPanelMapsLayout);
        mPanelMapsLayout.setHorizontalGroup(
                mPanelMapsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 670, Short.MAX_VALUE)
        );
        mPanelMapsLayout.setVerticalGroup(
                mPanelMapsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 277, Short.MAX_VALUE)
        );

        mMenuFile.setText("File");

        mMenuItemList.setText("List");
        mMenuItemList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mMenuItemListActionPerformed(evt);
            }
        });
        mMenuFile.add(mMenuItemList);

        mMenuItemUpload.setText("Upload");
        mMenuItemUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mMenuItemUploadActionPerformed(evt);
            }
        });
        mMenuFile.add(mMenuItemUpload);

        mMenuBar.add(mMenuFile);

        setJMenuBar(mMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(mPanelMaps, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(mPanelMaps, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mMenuItemUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mMenuItemUploadActionPerformed
        Upload1841720246Reza upload = new Upload1841720246Reza();
        upload.setVisible(true);
    }//GEN-LAST:event_mMenuItemUploadActionPerformed

    private void mMenuItemListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mMenuItemListActionPerformed
        List1841720019Sultan list = new List1841720019Sultan();
        list.setVisible(true);
    }//GEN-LAST:event_mMenuItemListActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main1841720019Sultan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main1841720019Sultan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main1841720019Sultan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main1841720019Sultan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main1841720019Sultan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar mMenuBar;
    private javax.swing.JMenu mMenuFile;
    private javax.swing.JMenuItem mMenuItemList;
    private javax.swing.JMenuItem mMenuItemUpload;
    private javax.swing.JPanel mPanelMaps;
    // End of variables declaration//GEN-END:variables
}
